//! Dedicated table administration SQL and Postgres execution.

use tokio_postgres::Client;

use super::{map_tokio_postgres_error, IpcErrorKind, MappedIpcError};

fn quote_identifier(identifier: &str) -> String {
    format!("\"{}\"", identifier.replace('"', "\"\""))
}

pub fn truncate_table_sql(schema: &str, table: &str) -> String {
    format!(
        "TRUNCATE TABLE {}.{}",
        quote_identifier(schema),
        quote_identifier(table)
    )
}

pub fn drop_table_sql(schema: &str, table: &str, table_type: Option<&str>) -> String {
    let command = if table_type == Some("foreign") {
        "DROP FOREIGN TABLE"
    } else {
        "DROP TABLE"
    };
    format!(
        "{} {}.{}",
        command,
        quote_identifier(schema),
        quote_identifier(table)
    )
}

pub fn generate_table_ddl_sql(schema: &str, table: &str) -> String {
    let schema_literal = schema.replace('\'', "''");
    let table_literal = table.replace('\'', "''");
    format!(
        r#"
WITH table_info AS (
  SELECT
    EXISTS (SELECT 1 FROM information_schema.tables
            WHERE table_schema = '{schema}' AND table_name = '{table}') AS is_regular,
    EXISTS (SELECT 1 FROM information_schema.foreign_tables
            WHERE foreign_table_schema = '{schema}' AND foreign_table_name = '{table}') AS is_foreign
),
cols AS (
  SELECT
    a.attname AS column_name,
    pg_catalog.format_type(a.atttypid, a.atttypmod) AS column_type,
    CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END AS not_null,
    CASE WHEN a.atthasdef THEN ' DEFAULT ' || pg_catalog.pg_get_expr(d.adbin, d.adrelid) ELSE '' END AS col_default,
    CASE WHEN a.attidentity = 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
         WHEN a.attidentity = 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
         WHEN a.attgenerated = 's' THEN ' GENERATED ALWAYS AS (' || pg_catalog.pg_get_expr(d.adbin, d.adrelid) || ') STORED'
         ELSE '' END AS identity_or_generated,
    a.attnum
  FROM pg_catalog.pg_attribute a
  JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
  JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
  LEFT JOIN pg_catalog.pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
  WHERE n.nspname = '{schema}' AND c.relname = '{table}'
    AND a.attnum > 0 AND NOT a.attisdropped
  ORDER BY a.attnum
),
col_defs AS (
  SELECT string_agg(
    format('  %I %s', column_name, column_type) || not_null || identity_or_generated ||
      CASE WHEN identity_or_generated = '' THEN col_default ELSE '' END,
    E',\n' ORDER BY attnum
  ) AS body FROM cols
),
constraints AS (
  SELECT string_agg(
    '  CONSTRAINT ' || format('%I', con.conname) || ' ' ||
      pg_catalog.pg_get_constraintdef(con.oid, true),
    E',\n' ORDER BY con.conname
  ) AS body
  FROM pg_catalog.pg_constraint con
  JOIN pg_catalog.pg_class c ON c.oid = con.conrelid
  JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = '{schema}' AND c.relname = '{table}'
),
indexes AS (
  SELECT string_agg(
    pg_catalog.pg_get_indexdef(i.indexrelid) || ';',
    E'\n' ORDER BY i.indexrelid
  ) AS body
  FROM pg_catalog.pg_index i
  JOIN pg_catalog.pg_class c ON c.oid = i.indrelid
  JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
  LEFT JOIN pg_catalog.pg_constraint con ON con.conindid = i.indexrelid
  WHERE n.nspname = '{schema}' AND c.relname = '{table}'
    AND con.oid IS NULL
)
SELECT
  (ti.is_regular OR ti.is_foreign) AS found,
  CASE WHEN ti.is_foreign THEN 'CREATE FOREIGN TABLE' ELSE 'CREATE TABLE' END
    || ' {quoted} (' || E'\n'
    || col_defs.body
    || COALESCE(E',\n' || constraints.body, '')
    || E'\n)'
    || CASE WHEN ti.is_foreign THEN
         COALESCE(' SERVER ' || (
           SELECT fs.srvname FROM information_schema.foreign_tables ft
           JOIN pg_catalog.pg_foreign_server fs ON fs.srvname = ft.foreign_server_name
           WHERE ft.foreign_table_schema = '{schema}' AND ft.foreign_table_name = '{table}'
           LIMIT 1
         ), '')
       ELSE '' END
    || ';'
    || COALESCE(E'\n' || indexes.body, '') AS ddl
FROM table_info ti, col_defs, constraints, indexes
"#,
        schema = schema_literal,
        table = table_literal,
        quoted = format!("{}.{}", quote_identifier(schema), quote_identifier(table)),
    )
}

pub fn set_search_path_sql(schema: Option<&str>) -> String {
    match schema {
        Some(schema) => format!("SET search_path TO {}, public", quote_identifier(schema)),
        None => "SET search_path TO public".into(),
    }
}

pub async fn truncate_table(
    client: &Client,
    schema: &str,
    table: &str,
) -> Result<(), MappedIpcError> {
    client
        .batch_execute(&truncate_table_sql(schema, table))
        .await
        .map_err(|e| map_tokio_postgres_error(&e))
}

pub async fn drop_table(
    client: &Client,
    schema: &str,
    table: &str,
    table_type: Option<&str>,
) -> Result<(), MappedIpcError> {
    client
        .batch_execute(&drop_table_sql(schema, table, table_type))
        .await
        .map_err(|e| map_tokio_postgres_error(&e))
}

pub async fn generate_table_ddl(
    client: &Client,
    schema: &str,
    table: &str,
) -> Result<String, MappedIpcError> {
    let row = client
        .query_one(&generate_table_ddl_sql(schema, table), &[])
        .await
        .map_err(|e| map_tokio_postgres_error(&e))?;
    let found: bool = row.try_get(0).map_err(|e| map_tokio_postgres_error(&e))?;
    let ddl: Option<String> = row.try_get(1).map_err(|e| map_tokio_postgres_error(&e))?;
    if !found {
        return Err(MappedIpcError {
            kind: IpcErrorKind::Unknown,
            message: "Table not found.".into(),
            position: None,
        });
    }
    Ok(ddl.unwrap_or_else(|| {
        format!(
            "CREATE TABLE {}.{} ()",
            quote_identifier(schema),
            quote_identifier(table)
        )
    }))
}

pub async fn set_search_path(client: &Client, schema: Option<&str>) -> Result<(), MappedIpcError> {
    client
        .batch_execute(&set_search_path_sql(schema))
        .await
        .map_err(|e| map_tokio_postgres_error(&e))
}

#[cfg(test)]
mod tests {
    use super::{drop_table_sql, generate_table_ddl_sql, set_search_path_sql, truncate_table_sql};

    #[test]
    fn truncate_and_drop_sql_quote_schema_and_table() {
        assert_eq!(
            truncate_table_sql("public", "temp"),
            r#"TRUNCATE TABLE "public"."temp""#
        );
        assert_eq!(
            drop_table_sql("public", "temp", None),
            r#"DROP TABLE "public"."temp""#
        );
        assert_eq!(
            drop_table_sql("public", "remote_orders", Some("foreign")),
            r#"DROP FOREIGN TABLE "public"."remote_orders""#
        );
        assert!(!truncate_table_sql("public", "temp").contains("public.temp"));
    }

    #[test]
    fn set_search_path_named_vs_all_schemas() {
        assert_eq!(
            set_search_path_sql(Some("audit")),
            r#"SET search_path TO "audit", public"#
        );
        assert_eq!(set_search_path_sql(None), "SET search_path TO public");
    }

    #[test]
    fn generate_table_ddl_sql_targets_quoted_table() {
        let sql = generate_table_ddl_sql("public", "orders");
        assert!(sql.contains("\"public\""));
        assert!(sql.contains("\"orders\""));
        assert!(sql.contains("EXISTS"));
        assert!(sql.contains("found"));
    }

    #[test]
    fn generate_table_ddl_sql_includes_defaults_and_constraints() {
        let sql = generate_table_ddl_sql("public", "orders");
        // DDL must include column defaults (e.g. DEFAULT now())
        assert!(
            sql.contains("column_default") || sql.contains("pg_get_expr"),
            "DDL query must retrieve column default values"
        );
        // DDL must include type modifiers (character_maximum_length / numeric_precision)
        assert!(
            sql.contains("character_maximum_length") || sql.contains("format_type"),
            "DDL query must retrieve full type with modifiers (e.g. varchar(50))"
        );
        // DDL must include primary key constraints
        assert!(
            sql.contains("pg_constraint") || sql.contains("contype"),
            "DDL query must retrieve primary key / unique / check constraints"
        );
    }

    #[test]
    fn generate_table_ddl_sql_must_not_hardcode_create_table() {
        let sql = generate_table_ddl_sql("public", "remote_orders");
        let create_table_literal = "'CREATE TABLE ";
        assert!(
            !sql.contains(create_table_literal),
            "DDL must not hardcode 'CREATE TABLE' — must be dynamic for foreign tables"
        );
    }

    #[test]
    fn generate_table_ddl_sql_output_structure() {
        let sql = generate_table_ddl_sql("public", "orders");

        // Output DDL must include DEFAULT expressions for columns
        assert!(
            sql.contains("atthasdef") && sql.contains("pg_get_expr"),
            "DDL must emit DEFAULT via pg_get_expr for columns with defaults"
        );

        // Output must format columns with indent (2 spaces + %I %s pattern)
        assert!(
            sql.contains("'  %I %s'"),
            "DDL must emit indented column definitions"
        );

        // Constraints section must use pg_get_constraintdef for full constraint text
        assert!(
            sql.contains("pg_get_constraintdef"),
            "DDL must use pg_get_constraintdef for PK/FK/UNIQUE/CHECK output"
        );

        // Indexes section must use pg_get_indexdef for CREATE INDEX statements
        assert!(
            sql.contains("pg_get_indexdef"),
            "DDL must use pg_get_indexdef for non-constraint indexes"
        );

        // Identity/generated column handling
        assert!(
            sql.contains("attidentity") && sql.contains("attgenerated"),
            "DDL must handle IDENTITY and GENERATED columns"
        );

        // Foreign table output must include SERVER clause
        assert!(
            sql.contains("SERVER") && sql.contains("srvname"),
            "DDL must include SERVER for foreign tables"
        );

        // Output must use CASE for conditional CREATE TABLE vs CREATE FOREIGN TABLE
        assert!(
            sql.contains("CASE WHEN ti.is_foreign THEN 'CREATE FOREIGN TABLE'"),
            "DDL must conditionally output CREATE FOREIGN TABLE"
        );
    }
}
