/** English chrome copy for the table browser (creative-brief sentence case). */
export const TablesCopy = {
  expandColumns: "Expand columns",
  collapseColumns: "Collapse columns",
  primaryKey: "Primary key",
  foreignKey: "Foreign key",
  foreignTable: "Foreign table",
  unique: "Unique",
  menu: "Table actions",
  refresh: "Refresh",
  ddl: "Show DDL",
  export: "Export",
  truncate: "Truncate",
  drop: "Drop",
  confirmDrop: "Drop table",
  confirmTruncate: "Truncate table",
  cancel: "Cancel",
  copy: "Copy",
  done: "Done",
  nextPage: "Next",
  loadMore: "Load more",
  ddlTitle: "Table DDL",
  exportTitle: "Export table",
  exportCsv: "Export CSV",
  exportJson: "Export JSON",
  dropPrompt: "Drop this table? This cannot be undone.",
  truncatePrompt: "Remove all rows from this table? This cannot be undone.",
  dropFailed: "Could not drop this table. Try again.",
  truncateFailed: "Could not truncate this table. Try again.",
  exportFailed: "Could not export this table. Try again.",
  ddlFailed: "Could not generate the DDL. Try again.",
  searchTables: "Search tables",
  noMatchingTables: "No matching tables",
  filterBySchema: "Filter by schema",
  allSchemas: "All schemas",
  ok: "OK",
  schemaError: "Could not set the schema search path.",
} as const;
