/** English chrome copy for the table browser (creative-brief sentence case). */
export const TablesCopy = {
  expandColumns: "Expand columns",
  collapseColumns: "Collapse columns",
  primaryKey: "Primary key",
  foreignKey: "Foreign key",
  foreignTable: "Foreign table",
  unique: "Unique",
  menu: "Table actions",
  refresh: "Refresh",
  ddl: "Show DDL",
  export: "Export",
  truncate: "Truncate",
  drop: "Drop",
  confirmDrop: "Drop table",
  confirmTruncate: "Truncate table",
  cancel: "Cancel",
  copy: "Copy",
  done: "Done",
  nextPage: "Next",
  ddlTitle: "Table DDL",
  exportTitle: "Export table",
  exportCsv: "Export CSV",
  exportJson: "Export JSON",
  dropPrompt: "Drop this table? This cannot be undone.",
  truncatePrompt: "Remove all rows from this table? This cannot be undone.",
  exportFailed: "Could not export this table. Try again.",
} as const;
